name: SonarQube

on:
  push:
    branches:
      - main
      - release
      - develop
  pull_request:
    branches:
      - main
      - release
      - develop

env:
  SLN_NAME: GestionTramitesSep
  DOTNET_VERSION: '6.0'
  GITHUB_TOKEN: ${{secrets.GITHUBTOKEN}}
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
            node-version: '14'   
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - uses: microsoft/setup-msbuild@v1
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Restore NuGet packages
        run: nuget restore 'GestionTramitesSep.sln'
      - name: Install dotnet-sonarscanner
        run: dotnet tool install --global dotnet-sonarscanner
      - name: Begin Sonar scan
        run: dotnet sonarscanner begin 
            /o:gamatron7devops 
            /k:gamatramites 
            /d:sonar.cs.opencover.reportsPaths=${{ env.SLN_NAME }}.Test/coverage.opencover.xml 
            /d:sonar.coverage.exclusions="**Test*.cs,**/Models/*,**Program.cs,**Startup.cs,**cshtml.cs,**.ts,**.js" 
            /d:sonar.exclusions="**/Scripts/*,**.ts,**.js" 
            /d:sonar.login=${{ secrets.SONAR_TOKEN }}
            /d:sonar.host.url=https://sonarcloud.io
      - name: restore
        run: dotnet restore
      - name: build
        run: dotnet build
      - name: Test
        run : dotnet test ${{ env.SLN_NAME }}.Test/${{ env.SLN_NAME }}.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - name: End Sonar scan
        run: dotnet sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}
